# Indicates that the windowsservercore image will be used as the base image.
FROM mcr.microsoft.com/windows/servercore:ltsc2019

RUN mkdir c:\apps

ADD portunus.exe c:/apps

# Sets a command or process that will run each time a container is run from the new image.
CMD [ "c:/apps/portunus.exe" ]