apiVersion: apps/v1
kind: Deployment
metadata:
  name: portunus
  labels:
    app: portunus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portunus
  template:
    metadata:
      labels:
        app: portunus
    spec:
      containers:
      - name: portunus
        image: quay.io/xphyr/portunus:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30