name: Build

on:
  push:
    branches:
      - "*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: quay.io/xphyr/portunus
        tags: ${{ github.sha }}
        containerfiles: |
          ./Dockerfile