name: Build

on:
  push:
    branches:
      - "*"

env:
  REGISTRY_USER: xphyr
  QUAY_IMAGE_REGISTRY: quay.io
  GHCR_IMAGE_REGISTRY: ghcr.io
  GHCR_REGISTRY_USER: ${{ github.actor }}
  GHCR_REGISTRY_PASSWORD: ${{ github.token }}
  QUAY_REGISTRY_PASSWORD: ${{ secrets.QUAY_REGISTRY_PASSWORD }}

jobs:

  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  container-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ghcr.io/xphyr/portunus
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Podman Login
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.GHCR_REGISTRY_USER }}
        password: ${{ env.GHCR_REGISTRY_PASSWORD }}
        registry: ${{ env.GHCR_IMAGE_REGISTRY }}

    - name: Push To ghcr.io
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.GHCR_IMAGE_REGISTRY }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"